version: '3.9'

services:
  db:
    image: 'dbtest'
    env_file:
      - "./global.env"
    # environment:
    #   - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    volumes:
      - data:/var/lib/mysql
    ports:
      - '8082:3306'
  flask:
    image: 'flasktest'
    ports:
      - "8081:80"
    volumes:
      - ./flask:/topProject/app
    depends_on:
      - db
    env_file:
      - "./global.env"
volumes:
  data: