FROM continuumio/miniconda3

WORKDIR /topProject

RUN pip install flask
RUN pip install PyMySQL
RUN pip install google-api-python-client

COPY . ./app

ENV FLASK_APP app 
ENV FLASK_ENV development

RUN set FLASK_APP=$FLASK_APP
RUN set FLASK_ENV=$FLASK_ENV

EXPOSE 8081

CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]

